package sanitize

import (
	"strings"
	"testing"
)

func TestStripsANSI(t *testing.T) {
	in := "\x1b[1mbold\x1b[22m and \x1b[0Kclear"
	got := Sanitize(in)
	if strings.Contains(got, "\x1b") {
		t.Fatalf("ESC byte survived: %q", got)
	}
	if got != "bold and clear" {
		t.Errorf("got %q, want %q", got, "bold and clear")
	}
}

func TestStripsC0ControlsKeepsTabNewline(t *testing.T) {
	in := "a\x00b\x07c\r\nd\te"
	got := Sanitize(in)
	want := "abc\nd\te"
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestUnwrapsClaudeCodeWrappers(t *testing.T) {
	cases := []struct{ in, want string }{
		{"<command-name>/model</command-name>", "/model"},
		{"<local-command-stdout>Kept model as Default</local-command-stdout>", "Kept model as Default"},
		{"<task-notification>done</task-notification>", "done"},
		{"<COMMAND-MESSAGE>hi</COMMAND-MESSAGE>", "hi"}, // case-insensitive
		{"<command-args></command-args>", ""},
		// The caveat block is DROPPED entirely (content included), not unwrapped.
		{"<local-command-caveat>Caveat: x</local-command-caveat>", ""},
	}
	for _, c := range cases {
		if got := Sanitize(c.in); got != c.want {
			t.Errorf("Sanitize(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

// TestDropsCaveatBlockEntirely covers CAPQ D2: the caveat boilerplate block is
// removed wholesale (content included), even multi-line, while genuine text
// around it survives and other wrappers still unwrap normally.
func TestDropsCaveatBlockEntirely(t *testing.T) {
	in := "before\n<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>\nafter"
	got := Sanitize(in)
	if strings.Contains(got, "Caveat: The messages below") {
		t.Errorf("caveat boilerplate survived: %q", got)
	}
	if !strings.Contains(got, "before") || !strings.Contains(got, "after") {
		t.Errorf("genuine surrounding text dropped: %q", got)
	}

	// Multi-line caveat body + an adjacent real wrapper that must still unwrap.
	multi := "<local-command-caveat>Caveat: line one\nline two</local-command-caveat><command-name>/clear</command-name>"
	got = Sanitize(multi)
	if strings.Contains(got, "Caveat") || strings.Contains(got, "line two") {
		t.Errorf("multi-line caveat survived: %q", got)
	}
	if strings.TrimSpace(got) != "/clear" {
		t.Errorf("adjacent wrapper not unwrapped: %q", got)
	}
}

func TestUnescapesLiteralNewlinesTabs(t *testing.T) {
	got := Sanitize(`foo\nbar\tbaz`)
	want := "foo\nbar\tbaz"
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSecretBuriedInANSIIsExposed(t *testing.T) {
	// A token split by an ANSI reset right after the prefix would be invisible to
	// a provider regex until sanitization removes the escape. We only assert here
	// that the ANSI is gone and the token is contiguous; redaction ordering is
	// covered in the cmd package where both packages run together.
	in := "ghp_\x1b[0mABCDEFGHIJKLMNOPQRSTUVWXYZ012345"
	got := Sanitize(in)
	if strings.Contains(got, "\x1b") {
		t.Fatalf("ESC survived: %q", got)
	}
	if !strings.HasPrefix(got, "ghp_ABCDEFGHIJ") {
		t.Errorf("token not contiguous after sanitize: %q", got)
	}
}

func TestIdempotent(t *testing.T) {
	in := "<command-name>/exit\x1b[0m</command-name>"
	once := Sanitize(in)
	twice := Sanitize(once)
	if once != twice {
		t.Errorf("not idempotent: %q != %q", once, twice)
	}
}

func TestEmptyAndStrings(t *testing.T) {
	if Sanitize("") != "" {
		t.Error("empty should stay empty")
	}
	if Strings(nil) != nil {
		t.Error("nil slice should stay nil")
	}
	got := Strings([]string{"\x1b[1ma", "<command-name>b</command-name>"})
	if got[0] != "a" || got[1] != "b" {
		t.Errorf("Strings = %v", got)
	}
}
